ACCOUNT_DB: host=127.0.0.1 user=debug password=Wm+it!(yz<[EQRr3 dbname=multiverse port=5432 sslmode=disable
JWT_KEY: fELMB#NT82ZrgxXUR8Sj0t&I@725ARLN
OAUTH2_PRIVATE_KEY: file://data/rs256-private.pem
MAIL_HOST: smtp.zoho.com
MAIL_PORT: 587
MAIL_USER: support@multiverse.direct
MAIL_PASSWORD: nXZn*SOW6avYB^Js
MAIL_SENDER: support@multiverse.direct