ACCOUNT_DB: host=192.168.122.61 user=huable password=Wm+it!(yz<[EQRr3 dbname=multiverse port=5432 sslmode=disable
JWT_KEY: fELMB#NT82ZrgxXUR8Sj0t&I@725ARLN
OAUTH2_PRIVATE_KEY: file://runtime/data/rs256-private.pem
OAUTH2_PUBLIC_KEY: file://runtime/data/rs256-public.pem
OAUTH2_JWK: file://runtime/data/rs256-jwk.json
WEB_URL: https://portal.calieo.dev
SELF_URL: https://portal.calieo.dev
RESOURCE_URL: https://fields.calieo.dev
MAIL_HOST: smtp.zoho.com
MAIL_PORT: 587
MAIL_USER: support@multiverse.direct
MAIL_PASSWORD: nXZn*SOW6avYB^Js
MAIL_SENDER: support@multiverse.direct
RPID: portal.calieo.dev
RPOrigins: https://portal.calieo.dev