FROM ubuntu:21.10

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y build-essential \
      gcc \
      g++ \
      gdb \
      clang \
      make \
      ninja-build \
      cmake \
      tar \
      openssh-server \
      rsync \
      gcc-multilib \
      libbpf-dev \
  && apt-get clean

RUN echo 'root:password' | chpasswd \
    && echo "Port 22" >> /etc/ssh/sshd_config \
    && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config \
    && mkdir /run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]