name: venus

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.5.0"

flutter:
  uses-material-design: true
  assets:
    - static/images/
    - static/images/icons/
    - static/images/placeholder/
    - static/sql/

dependencies:
  flutter:
    sdk: flutter
  http:
  provider: ^6.0.5
  path: ^1.8.2
  flutter_svg: ^2.0.7
  uuid: ^4.0.0
  syncfusion_flutter_datepicker: ^24.2.7
  syncfusion_flutter_calendar: ^24.2.7
  url_strategy: ^0.2.0
  validators: ^3.0.0
  split_view: ^3.1.0
  flutter_riverpod: ^2.1.3
  flutter_screenutil: ^5.6.0
  json_annotation: ^4.7.0
  flutter_staggered_grid_view: ^0.7.0
  markdown: ^7.1.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^2.2.0
  loading_indicator: ^3.1.0
  mime: ^1.0.3
  file_picker: ^6.1.1
  path_provider: ^2.0.11
  go_router: ^13.2.0
  logger: ^2.0.2
  crypto: ^3.0.2
  flutter_sharing_intent:
    path: ./plugins/flutter_sharing_intent
  image_picker: ^1.0.4
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: any
  json_serializable: ^6.5.1
