name: polaris

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.7.0"

flutter:
  uses-material-design: true

  assets:
    - static/images/
    - static/images/icons/
    - static/images/placeholder/

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  path: ^1.8.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_svg: ^0.22.0
  uuid: ^3.0.4
  syncfusion_flutter_datepicker:
  syncfusion_flutter_calendar:
  url_strategy: ^0.2.0
  validators: ^3.0.0
  split_view: ^3.1.0
  flutter_riverpod: ^2.0.0
  flutter_screenutil: ^5.5.4
  json_annotation: ^4.7.0
  flutter_staggered_grid_view: ^0.6.2
  markdown: ^6.0.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^1.3.0+2
  loading_indicator: ^3.1.0
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator: ^2.0.0
  build_runner: any
  json_serializable: ^6.5.1