export class PSArticleModel {
    uid = ''
    urn = ''
    title = ''
    header = ''
    body = ''
    create_time = ''
    update_time = ''
    creator = ''
    keywords = ''
    description = ''
    cover = ''
    discover = 0
    owner = ''
    owner_name = ''
    channel = ''
    channel_name = ''
    partition = ''
    path = ''
}
